---
- name: Install Certbot
  yum:
    name: certbot
    state: present

- name: Copy Certbot configuration
  copy:
    src: files/cli.ini
    dest: /etc/letsencrypt/cli.ini
    owner: root
    group: root
    mode: 0644

- name: Remove useless dependencies
  yum:
    autoremove: yes